In [1]:
from sklearn.linear_model import LinearRegression

In [2]:
model = LinearRegression(normalize=True)
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)


In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
list(y)

[0, 1, 2, 3, 4]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3) # 30% test size by convention
X_train

array([[6, 7],
       [4, 5],
       [2, 3]])

In [7]:
y_train

[3, 2, 1]

In [8]:
X_test

array([[8, 9],
       [0, 1]])

In [9]:
y_test

[4, 0]

In [10]:
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [11]:
predictions = model.predict(X_test)